setup:
	./gradlew wrapper --gradle-version 8.14

run-dist:
	./build/install/app/bin/app $(ARGS)

run:
	./gradlew run

report:
	./gradlew jacocoTestReport

test:
	./gradlew test

lint:
	./gradlew checkstyleMain checkstyleTest

build:
	./gradlew build

install:
	./gradlew clean installDist

clean:
	./gradlew clean

update-deps:
	./gradlew dependencyUpdates

.PHONY: build